name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
          REPOSITORY: SepehrHariri/SepehrHariri # optional
          ### content
          SHOW_TOTAL_CODE_TIME: true 
          SHOW_LINES_OF_CODE: true 
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: => # optional
          CODE_LANG: python # optional
          TIME_RANGE: all_time # optional
          LANG_COUNT: 10 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          SHOW_DAYS_OF_WEEK: true 
          STOP_AT_OTHER: true # optional
          # IGNORED_LANGUAGES: YAML JSON TOML # optional
          SHOW_UPDATED_DATE: true 
          SHOW_OS: false 
          SHOW_PROJECTS: true 
           
          SHOW_PROFILE_VIEWS: false 
          SHOW_TIMEZONE: false 
          SHOW_LANGUAGE_PER_REPO: true 
          SYMBOL_VERSION: 2 
          SHOW_SHORT_INFO: true 
          SHOW_LANGUAGE: false # optional
          SHOW_EDITORS: true 
          
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: master # optional
          TARGET_PATH: README.md # optional
          COMMITTER_NAME: GitHubActionBot # optional
          COMMITTER_EMAIL: action-bot@github.com # optional
          AUTHOR_NAME: YOUR_NAME # optional
          AUTHOR_EMAIL: YOUR@EMAIL.com # optional
